#!/usr/bin/env bash

# Fail on first line that fails.
set -e

# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
if ! git diff-index --check --cached $against
then
    echo "Aborting commit due to whitespace errors."
    exit 1
fi

# Only keep staged files that are added (A), copied (C) or modified (M).
STAGED=$(git --no-pager diff --name-only --cached --diff-filter=ACM)
# Files which are only partly staged (eg. git add --patch).
PATCH_STAGED=$(git --no-pager diff --name-only --diff-filter=ACM $STAGED)
# Files which are fully staged.
FULLY_STAGED=$(comm -23 <(echo "$STAGED") <(echo "$PATCH_STAGED"))

JS_STAGED=$(grep .js$ <<< "$STAGED" || true)
JS_FULLY_STAGED=$(grep .js$ <<< "$FULLY_STAGED" || true)
SCSS_STAGED=$(grep .scss$ <<< "$STAGED" || true)
SCSS_FULLY_STAGED=$(grep .scss$ <<< "$FULLY_STAGED" || true)
MD_STAGED=$(grep .md$ <<< "$STAGED" || true)
MD_FULLY_STAGED=$(grep .md$ <<< "$FULLY_STAGED" || true)
YML_STAGED=$(grep .yml$ <<< "$STAGED" || true)
YML_FULLY_STAGED=$(grep .yml$ <<< "$FULLY_STAGED" || true)
YAML_STAGED=$(grep .yaml$ <<< "$STAGED" || true)
YAML_FULLY_STAGED=$(grep .yaml$ <<< "$FULLY_STAGED" || true)
SNAPSHOT_STAGED=$(grep .snap$ <<< "$STAGED" || true)
HTML_STAGED=$(grep .html$ <<< "$STAGED" || true)

# Uncomment for debugging help.
# tr ' ' '\n' <<< "STAGED $STAGED PATCH_STAGED $PATCH_STAGED FULLY_STAGED $FULLY_STAGED JS_STAGED $JS_STAGED JS_FULLY_STAGED $JS_FULLY_STAGED SNAPSHOT_STAGED $SNAPSHOT_STAGED"

if [ -n "$JS_FULLY_STAGED" ];
then
    # Format and re-stage fully staged files only.
    npm run formatter -s -- $JS_FULLY_STAGED
    git add $JS_FULLY_STAGED
fi

if [ -n "$JS_STAGED" ];
then
    npm run linter:js -s -- $JS_STAGED
fi

if [ -n "$SCSS_FULLY_STAGED" ];
then
    npm run formatter -s -- $SCSS_FULLY_STAGED
    git add $SCSS_FULLY_STAGED
fi

if [ -n "$SCSS_STAGED" ];
then
    npm run linter -s -- $SCSS_STAGED
fi

if [ -n "$MD_FULLY_STAGED" ];
then
    npm run formatter -s -- $MD_FULLY_STAGED
    git add $MD_FULLY_STAGED
fi

if [ -n "$MD_STAGED" ];
then
    npm run linter -s -- $MD_STAGED
fi

if [ -n "$YML_FULLY_STAGED" ];
then
    npm run formatter -s -- $YML_FULLY_STAGED
    git add $YML_FULLY_STAGED
fi

if [ -n "$YML_STAGED" ];
then
    npm run linter -s -- $YML_STAGED
fi

if [ -n "$YAML_FULLY_STAGED" ];
then
    npm run formatter -s -- $YAML_FULLY_STAGED
    git add $YAML_FULLY_STAGED
fi

if [ -n "$YAML_STAGED" ];
then
    npm run linter -s -- $YAML_STAGED
fi

if [ -n "$JS_STAGED" ] || [ -n "$SNAPSHOT_STAGED" ];
then
    npm run test:coverage -s
fi

if [ -n "$JS_STAGED" ] || [ -n "$SCSS_STAGED" ] || [ -n "$HTML_STAGED" ];
then
    npm run dist -s
    npm run test:integration -s
fi
