/* eslint-disable */
export default {
    entityMap: {},
    blocks: [
        {
            key: 'b4b1l',
            text: 'Unstyled',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: 'h3id',
            text: 'Header one',
            type: 'header-one',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: '3k5je',
            text: 'Header two',
            type: 'header-two',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: '4mv7l',
            text: 'Header three',
            type: 'header-three',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: '2ulum',
            text: 'Header four',
            type: 'header-four',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: 'fdif3',
            text: 'Header five',
            type: 'header-five',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: 'f1g6d',
            text: 'Header six',
            type: 'header-six',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: 'cm3n2',
            text: 'Unordered list item',
            type: 'unordered-list-item',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: 'ct6kt',
            text: 'Ordered list istem',
            type: 'ordered-list-item',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: 'fu7tq',
            text: 'Blockquote',
            type: 'blockquote',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: '9fh29',
            text: 'Code',
            type: 'code-block',
            depth: 0,
            inlineStyleRanges: [],
            entityRanges: [],
            data: {},
        },
        {
            key: 'bsahk',
            text: 'Bold: Bold',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 6, length: 4, style: 'BOLD' }],
            entityRanges: [],
            data: {},
        },
        {
            key: '3a0b9',
            text: 'Italic: Italic',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 8, length: 6, style: 'ITALIC' }],
            entityRanges: [],
            data: {},
        },
        {
            key: '21o6k',
            text: 'Code: Code',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 6, length: 4, style: 'CODE' }],
            entityRanges: [],
            data: {},
        },
        {
            key: 'ek19e',
            text: 'Underline: Underline',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 11, length: 9, style: 'UNDERLINE' }],
            entityRanges: [],
            data: {},
        },
        {
            key: '598at',
            text: 'Strikethrough: Strikethrough',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [
                { offset: 15, length: 13, style: 'STRIKETHROUGH' },
            ],
            entityRanges: [],
            data: {},
        },
        {
            key: 'bi1qo',
            text: 'Mark: Mark',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 6, length: 4, style: 'MARK' }],
            entityRanges: [],
            data: {},
        },
        {
            key: '8csv9',
            text: 'Quotation: Quotation',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 11, length: 9, style: 'QUOTATION' }],
            entityRanges: [],
            data: {},
        },
        {
            key: '60nd0',
            text: 'Small: Small',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 7, length: 5, style: 'SMALL' }],
            entityRanges: [],
            data: {},
        },
        {
            key: '6196j',
            text: 'Sample: Sample',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 8, length: 6, style: 'SAMPLE' }],
            entityRanges: [],
            data: {},
        },
        {
            key: 'ecjnv',
            text: 'Insert: Insert',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 8, length: 6, style: 'INSERT' }],
            entityRanges: [],
            data: {},
        },
        {
            key: '1r1sp',
            text: 'Delete: Delete',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 8, length: 6, style: 'DELETE' }],
            entityRanges: [],
            data: {},
        },
        {
            key: 'e19ip',
            text: 'Keyboard: Keyboard',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 10, length: 8, style: 'KEYBOARD' }],
            entityRanges: [],
            data: {},
        },
        {
            key: 'f8mhq',
            text: 'Superscript: Superscript',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [
                { offset: 13, length: 11, style: 'SUPERSCRIPT' },
            ],
            entityRanges: [],
            data: {},
        },
        {
            key: '2nie8',
            text: 'Subscript: Subscript',
            type: 'unstyled',
            depth: 0,
            inlineStyleRanges: [{ offset: 11, length: 9, style: 'SUBSCRIPT' }],
            entityRanges: [],
            data: {},
        },
    ],
};
